-- Rode este SQL no Supabase em: SQL Editor > New query > Run.
-- Ele cria a tabela usada pelo formulario de leads da SmartLuup.

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  nome text not null,
  empresa text not null,
  whatsapp text not null,
  email text,
  segmento text,
  tipo_projeto text not null,
  objetivo text not null,
  prazo text,
  orcamento text,
  detalhes text,
  criado_em timestamp with time zone not null default now()
);

-- Para o app Python do servidor inserir leads usando a anon key,
-- deixe RLS desligado nessa tabela ou crie uma policy de insert.
-- Recomendacao simples para comecar: criar a tabela e testar primeiro.
